/**
 * Be[Country] Platform — World Data Registry
 *
 * COMPLETE dataset of all 193 UN member states and ~70 most spoken languages.
 * Used for country gates, compass routing, pioneer onboarding, and matching.
 *
 * Data sources: UN member state list, ISO 3166-1 alpha-2, ISO 639-1, ISO 4217.
 * Geographic coordinates are approximate country centroids.
 *
 * DO NOT duplicate this data elsewhere. Import from here.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface WorldCountry {
  code: string // ISO 3166-1 alpha-2
  name: string // English name
  region: string // Africa, Europe, Asia, Americas, Oceania
  subregion: string // East Africa, Western Europe, etc.
  lat: number
  lng: number
  languages: string[] // Primary language codes (ISO 639-1)
  faiths: string[] // Predominant faiths
  currency: string // ISO 4217
}

export interface WorldLanguage {
  code: string
  name: string
  nativeName: string
  script: 'ltr' | 'rtl'
  speakers: number // Approximate millions
  countries: string[] // Where widely spoken
}

// ─────────────────────────────────────────────────────────────────────────────
// 193 UN Member States
// ─────────────────────────────────────────────────────────────────────────────

export const WORLD_COUNTRIES: Record<string, WorldCountry> = {
  // ═══════════════════════════════════════════════════════════════════════════
  // AFRICA (54 countries)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── East Africa ──
  KE: {
    code: 'KE',
    name: 'Kenya',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 0.0236,
    lng: 37.9062,
    languages: ['en', 'sw'],
    faiths: ['Christianity', 'Islam'],
    currency: 'KES',
  },
  TZ: {
    code: 'TZ',
    name: 'Tanzania',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -6.369,
    lng: 34.8888,
    languages: ['sw', 'en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'TZS',
  },
  UG: {
    code: 'UG',
    name: 'Uganda',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 1.3733,
    lng: 32.2903,
    languages: ['en', 'sw'],
    faiths: ['Christianity', 'Islam'],
    currency: 'UGX',
  },
  RW: {
    code: 'RW',
    name: 'Rwanda',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -1.9403,
    lng: 29.8739,
    languages: ['rw', 'en', 'fr'],
    faiths: ['Christianity'],
    currency: 'RWF',
  },
  BI: {
    code: 'BI',
    name: 'Burundi',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -3.3731,
    lng: 29.9189,
    languages: ['rw', 'fr'],
    faiths: ['Christianity'],
    currency: 'BIF',
  },
  ET: {
    code: 'ET',
    name: 'Ethiopia',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 9.145,
    lng: 40.4897,
    languages: ['am', 'en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'ETB',
  },
  ER: {
    code: 'ER',
    name: 'Eritrea',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 15.1794,
    lng: 39.7823,
    languages: ['ti', 'ar', 'en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'ERN',
  },
  DJ: {
    code: 'DJ',
    name: 'Djibouti',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 11.8251,
    lng: 42.5903,
    languages: ['fr', 'ar', 'so'],
    faiths: ['Islam'],
    currency: 'DJF',
  },
  SO: {
    code: 'SO',
    name: 'Somalia',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 5.1521,
    lng: 46.1996,
    languages: ['so', 'ar'],
    faiths: ['Islam'],
    currency: 'SOS',
  },
  SS: {
    code: 'SS',
    name: 'South Sudan',
    region: 'Africa',
    subregion: 'East Africa',
    lat: 6.877,
    lng: 31.307,
    languages: ['en'],
    faiths: ['Christianity', 'Traditional'],
    currency: 'SSP',
  },
  SC: {
    code: 'SC',
    name: 'Seychelles',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -4.6796,
    lng: 55.492,
    languages: ['en', 'fr'],
    faiths: ['Christianity'],
    currency: 'SCR',
  },
  KM: {
    code: 'KM',
    name: 'Comoros',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -11.6455,
    lng: 43.3333,
    languages: ['ar', 'fr'],
    faiths: ['Islam'],
    currency: 'KMF',
  },
  MU: {
    code: 'MU',
    name: 'Mauritius',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -20.3484,
    lng: 57.5522,
    languages: ['en', 'fr'],
    faiths: ['Hinduism', 'Christianity', 'Islam'],
    currency: 'MUR',
  },
  MG: {
    code: 'MG',
    name: 'Madagascar',
    region: 'Africa',
    subregion: 'East Africa',
    lat: -18.7669,
    lng: 46.8691,
    languages: ['mg', 'fr'],
    faiths: ['Christianity', 'Traditional'],
    currency: 'MGA',
  },

  // ── Southern Africa ──
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -30.5595,
    lng: 22.9375,
    languages: ['zu', 'en'],
    faiths: ['Christianity'],
    currency: 'ZAR',
  },
  MW: {
    code: 'MW',
    name: 'Malawi',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -13.2543,
    lng: 34.3015,
    languages: ['en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'MWK',
  },
  MZ: {
    code: 'MZ',
    name: 'Mozambique',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -18.6657,
    lng: 35.5296,
    languages: ['pt'],
    faiths: ['Christianity', 'Islam', 'Traditional'],
    currency: 'MZN',
  },
  ZM: {
    code: 'ZM',
    name: 'Zambia',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -13.1339,
    lng: 27.8493,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'ZMW',
  },
  ZW: {
    code: 'ZW',
    name: 'Zimbabwe',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -19.0154,
    lng: 29.1549,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'ZWL',
  },
  BW: {
    code: 'BW',
    name: 'Botswana',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -22.3285,
    lng: 24.6849,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'BWP',
  },
  NA: {
    code: 'NA',
    name: 'Namibia',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -22.9576,
    lng: 18.4904,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'NAD',
  },
  SZ: {
    code: 'SZ',
    name: 'Eswatini',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -26.5225,
    lng: 31.4659,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'SZL',
  },
  LS: {
    code: 'LS',
    name: 'Lesotho',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -29.61,
    lng: 28.2336,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'LSL',
  },
  AO: {
    code: 'AO',
    name: 'Angola',
    region: 'Africa',
    subregion: 'Southern Africa',
    lat: -11.2027,
    lng: 17.8739,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'AOA',
  },

  // ── West Africa ──
  NG: {
    code: 'NG',
    name: 'Nigeria',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 9.082,
    lng: 8.6753,
    languages: ['en', 'ha', 'yo', 'ig'],
    faiths: ['Christianity', 'Islam'],
    currency: 'NGN',
  },
  GH: {
    code: 'GH',
    name: 'Ghana',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 7.9465,
    lng: -1.0232,
    languages: ['en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'GHS',
  },
  CI: {
    code: 'CI',
    name: "Cote d'Ivoire",
    region: 'Africa',
    subregion: 'West Africa',
    lat: 7.54,
    lng: -5.5471,
    languages: ['fr'],
    faiths: ['Islam', 'Christianity'],
    currency: 'XOF',
  },
  SN: {
    code: 'SN',
    name: 'Senegal',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 14.4974,
    lng: -14.4524,
    languages: ['fr'],
    faiths: ['Islam'],
    currency: 'XOF',
  },
  ML: {
    code: 'ML',
    name: 'Mali',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 17.5707,
    lng: -3.9962,
    languages: ['fr'],
    faiths: ['Islam'],
    currency: 'XOF',
  },
  BF: {
    code: 'BF',
    name: 'Burkina Faso',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 12.2383,
    lng: -1.5616,
    languages: ['fr'],
    faiths: ['Islam', 'Christianity'],
    currency: 'XOF',
  },
  NE: {
    code: 'NE',
    name: 'Niger',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 17.6078,
    lng: 8.0817,
    languages: ['fr', 'ha'],
    faiths: ['Islam'],
    currency: 'XOF',
  },
  GN: {
    code: 'GN',
    name: 'Guinea',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 9.9456,
    lng: -9.6966,
    languages: ['fr'],
    faiths: ['Islam'],
    currency: 'GNF',
  },
  SL: {
    code: 'SL',
    name: 'Sierra Leone',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 8.4606,
    lng: -11.7799,
    languages: ['en'],
    faiths: ['Islam', 'Christianity'],
    currency: 'SLE',
  },
  LR: {
    code: 'LR',
    name: 'Liberia',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 6.4281,
    lng: -9.4295,
    languages: ['en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'LRD',
  },
  TG: {
    code: 'TG',
    name: 'Togo',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 8.6195,
    lng: 0.8248,
    languages: ['fr'],
    faiths: ['Traditional', 'Christianity', 'Islam'],
    currency: 'XOF',
  },
  BJ: {
    code: 'BJ',
    name: 'Benin',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 9.3077,
    lng: 2.3158,
    languages: ['fr'],
    faiths: ['Christianity', 'Islam', 'Traditional'],
    currency: 'XOF',
  },
  MR: {
    code: 'MR',
    name: 'Mauritania',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 21.0079,
    lng: -10.9408,
    languages: ['ar', 'fr'],
    faiths: ['Islam'],
    currency: 'MRU',
  },
  GM: {
    code: 'GM',
    name: 'Gambia',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 13.4432,
    lng: -15.3101,
    languages: ['en'],
    faiths: ['Islam'],
    currency: 'GMD',
  },
  GW: {
    code: 'GW',
    name: 'Guinea-Bissau',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 11.8037,
    lng: -15.1804,
    languages: ['pt'],
    faiths: ['Islam', 'Traditional'],
    currency: 'XOF',
  },
  CV: {
    code: 'CV',
    name: 'Cabo Verde',
    region: 'Africa',
    subregion: 'West Africa',
    lat: 16.5388,
    lng: -23.0418,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'CVE',
  },

  // ── Central Africa ──
  CD: {
    code: 'CD',
    name: 'Democratic Republic of the Congo',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: -4.0383,
    lng: 21.7587,
    languages: ['fr', 'sw'],
    faiths: ['Christianity'],
    currency: 'CDF',
  },
  CG: {
    code: 'CG',
    name: 'Republic of the Congo',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: -0.228,
    lng: 15.8277,
    languages: ['fr'],
    faiths: ['Christianity'],
    currency: 'XAF',
  },
  CM: {
    code: 'CM',
    name: 'Cameroon',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: 7.3697,
    lng: 12.3547,
    languages: ['fr', 'en'],
    faiths: ['Christianity', 'Islam'],
    currency: 'XAF',
  },
  GA: {
    code: 'GA',
    name: 'Gabon',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: -0.8037,
    lng: 11.6094,
    languages: ['fr'],
    faiths: ['Christianity'],
    currency: 'XAF',
  },
  GQ: {
    code: 'GQ',
    name: 'Equatorial Guinea',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: 1.6508,
    lng: 10.2679,
    languages: ['es', 'fr', 'pt'],
    faiths: ['Christianity'],
    currency: 'XAF',
  },
  CF: {
    code: 'CF',
    name: 'Central African Republic',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: 6.6111,
    lng: 20.9394,
    languages: ['fr'],
    faiths: ['Christianity', 'Islam'],
    currency: 'XAF',
  },
  TD: {
    code: 'TD',
    name: 'Chad',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: 15.4542,
    lng: 18.7322,
    languages: ['fr', 'ar'],
    faiths: ['Islam', 'Christianity'],
    currency: 'XAF',
  },
  ST: {
    code: 'ST',
    name: 'Sao Tome and Principe',
    region: 'Africa',
    subregion: 'Central Africa',
    lat: 0.1864,
    lng: 6.6131,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'STN',
  },

  // ── North Africa ──
  EG: {
    code: 'EG',
    name: 'Egypt',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 26.8206,
    lng: 30.8025,
    languages: ['ar'],
    faiths: ['Islam', 'Christianity'],
    currency: 'EGP',
  },
  SD: {
    code: 'SD',
    name: 'Sudan',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 12.8628,
    lng: 30.2176,
    languages: ['ar', 'en'],
    faiths: ['Islam'],
    currency: 'SDG',
  },
  LY: {
    code: 'LY',
    name: 'Libya',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 26.3351,
    lng: 17.2283,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'LYD',
  },
  TN: {
    code: 'TN',
    name: 'Tunisia',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 33.8869,
    lng: 9.5375,
    languages: ['ar', 'fr'],
    faiths: ['Islam'],
    currency: 'TND',
  },
  DZ: {
    code: 'DZ',
    name: 'Algeria',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 28.0339,
    lng: 1.6596,
    languages: ['ar', 'fr'],
    faiths: ['Islam'],
    currency: 'DZD',
  },
  MA: {
    code: 'MA',
    name: 'Morocco',
    region: 'Africa',
    subregion: 'North Africa',
    lat: 31.7917,
    lng: -7.0926,
    languages: ['ar', 'fr'],
    faiths: ['Islam'],
    currency: 'MAD',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // EUROPE (44 countries)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Western Europe ──
  DE: {
    code: 'DE',
    name: 'Germany',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 51.1657,
    lng: 10.4515,
    languages: ['de'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  FR: {
    code: 'FR',
    name: 'France',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 46.2276,
    lng: 2.2137,
    languages: ['fr'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 52.1326,
    lng: 5.2913,
    languages: ['nl'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 50.5039,
    lng: 4.4699,
    languages: ['nl', 'fr', 'de'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  LU: {
    code: 'LU',
    name: 'Luxembourg',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 49.8153,
    lng: 6.1296,
    languages: ['fr', 'de'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  AT: {
    code: 'AT',
    name: 'Austria',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 47.5162,
    lng: 14.5501,
    languages: ['de'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  CH: {
    code: 'CH',
    name: 'Switzerland',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 46.8182,
    lng: 8.2275,
    languages: ['de', 'fr', 'it'],
    faiths: ['Christianity'],
    currency: 'CHF',
  },
  LI: {
    code: 'LI',
    name: 'Liechtenstein',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 47.166,
    lng: 9.5554,
    languages: ['de'],
    faiths: ['Christianity'],
    currency: 'CHF',
  },
  MC: {
    code: 'MC',
    name: 'Monaco',
    region: 'Europe',
    subregion: 'Western Europe',
    lat: 43.7384,
    lng: 7.4246,
    languages: ['fr'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },

  // ── Northern Europe ──
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 55.3781,
    lng: -3.436,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'GBP',
  },
  IE: {
    code: 'IE',
    name: 'Ireland',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 53.1424,
    lng: -7.6921,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  IS: {
    code: 'IS',
    name: 'Iceland',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 64.9631,
    lng: -19.0208,
    languages: ['is'],
    faiths: ['Christianity'],
    currency: 'ISK',
  },
  SE: {
    code: 'SE',
    name: 'Sweden',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 60.1282,
    lng: 18.6435,
    languages: ['sv'],
    faiths: ['Christianity'],
    currency: 'SEK',
  },
  NO: {
    code: 'NO',
    name: 'Norway',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 60.472,
    lng: 8.4689,
    languages: ['no'],
    faiths: ['Christianity'],
    currency: 'NOK',
  },
  DK: {
    code: 'DK',
    name: 'Denmark',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 56.2639,
    lng: 9.5018,
    languages: ['da'],
    faiths: ['Christianity'],
    currency: 'DKK',
  },
  FI: {
    code: 'FI',
    name: 'Finland',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 61.9241,
    lng: 25.7482,
    languages: ['fi', 'sv'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  EE: {
    code: 'EE',
    name: 'Estonia',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 58.5953,
    lng: 25.0136,
    languages: ['et'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  LV: {
    code: 'LV',
    name: 'Latvia',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 56.8796,
    lng: 24.6032,
    languages: ['lv'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  LT: {
    code: 'LT',
    name: 'Lithuania',
    region: 'Europe',
    subregion: 'Northern Europe',
    lat: 55.1694,
    lng: 23.8813,
    languages: ['lt'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },

  // ── Southern Europe ──
  ES: {
    code: 'ES',
    name: 'Spain',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 40.4637,
    lng: -3.7492,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  PT: {
    code: 'PT',
    name: 'Portugal',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 39.3999,
    lng: -8.2245,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 41.8719,
    lng: 12.5674,
    languages: ['it'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  GR: {
    code: 'GR',
    name: 'Greece',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 39.0742,
    lng: 21.8243,
    languages: ['el'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  MT: {
    code: 'MT',
    name: 'Malta',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 35.9375,
    lng: 14.3754,
    languages: ['mt', 'en'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  CY: {
    code: 'CY',
    name: 'Cyprus',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 35.1264,
    lng: 33.4299,
    languages: ['el', 'tr'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  AD: {
    code: 'AD',
    name: 'Andorra',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 42.5063,
    lng: 1.5218,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  SM: {
    code: 'SM',
    name: 'San Marino',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 43.9424,
    lng: 12.4578,
    languages: ['it'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  // Holy See (VA) is a UN observer state, not a member state
  AL: {
    code: 'AL',
    name: 'Albania',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 41.1533,
    lng: 20.1683,
    languages: ['sq'],
    faiths: ['Islam', 'Christianity'],
    currency: 'ALL',
  },
  MK: {
    code: 'MK',
    name: 'North Macedonia',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 41.5122,
    lng: 21.7453,
    languages: ['mk'],
    faiths: ['Christianity', 'Islam'],
    currency: 'MKD',
  },
  ME: {
    code: 'ME',
    name: 'Montenegro',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 42.7087,
    lng: 19.3744,
    languages: ['sr'],
    faiths: ['Christianity', 'Islam'],
    currency: 'EUR',
  },
  RS: {
    code: 'RS',
    name: 'Serbia',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 44.0165,
    lng: 21.0059,
    languages: ['sr'],
    faiths: ['Christianity'],
    currency: 'RSD',
  },
  BA: {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 43.9159,
    lng: 17.6791,
    languages: ['bs', 'hr', 'sr'],
    faiths: ['Islam', 'Christianity'],
    currency: 'BAM',
  },
  HR: {
    code: 'HR',
    name: 'Croatia',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 45.1,
    lng: 15.2,
    languages: ['hr'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  SI: {
    code: 'SI',
    name: 'Slovenia',
    region: 'Europe',
    subregion: 'Southern Europe',
    lat: 46.1512,
    lng: 14.9955,
    languages: ['sl'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },

  // ── Eastern Europe ──
  PL: {
    code: 'PL',
    name: 'Poland',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 51.9194,
    lng: 19.1451,
    languages: ['pl'],
    faiths: ['Christianity'],
    currency: 'PLN',
  },
  CZ: {
    code: 'CZ',
    name: 'Czechia',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 49.8175,
    lng: 15.473,
    languages: ['cs'],
    faiths: ['Christianity'],
    currency: 'CZK',
  },
  SK: {
    code: 'SK',
    name: 'Slovakia',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 48.669,
    lng: 19.699,
    languages: ['sk'],
    faiths: ['Christianity'],
    currency: 'EUR',
  },
  HU: {
    code: 'HU',
    name: 'Hungary',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 47.1625,
    lng: 19.5033,
    languages: ['hu'],
    faiths: ['Christianity'],
    currency: 'HUF',
  },
  RO: {
    code: 'RO',
    name: 'Romania',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 45.9432,
    lng: 24.9668,
    languages: ['ro'],
    faiths: ['Christianity'],
    currency: 'RON',
  },
  BG: {
    code: 'BG',
    name: 'Bulgaria',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 42.7339,
    lng: 25.4858,
    languages: ['bg'],
    faiths: ['Christianity'],
    currency: 'BGN',
  },
  UA: {
    code: 'UA',
    name: 'Ukraine',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 48.3794,
    lng: 31.1656,
    languages: ['uk'],
    faiths: ['Christianity'],
    currency: 'UAH',
  },
  MD: {
    code: 'MD',
    name: 'Moldova',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 47.4116,
    lng: 28.3699,
    languages: ['ro'],
    faiths: ['Christianity'],
    currency: 'MDL',
  },
  BY: {
    code: 'BY',
    name: 'Belarus',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 53.7098,
    lng: 27.9534,
    languages: ['be', 'ru'],
    faiths: ['Christianity'],
    currency: 'BYN',
  },
  RU: {
    code: 'RU',
    name: 'Russia',
    region: 'Europe',
    subregion: 'Eastern Europe',
    lat: 61.524,
    lng: 105.3188,
    languages: ['ru'],
    faiths: ['Christianity', 'Islam'],
    currency: 'RUB',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ASIA (48 countries)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── East Asia ──
  CN: {
    code: 'CN',
    name: 'China',
    region: 'Asia',
    subregion: 'East Asia',
    lat: 35.8617,
    lng: 104.1954,
    languages: ['zh'],
    faiths: ['Buddhism', 'Traditional'],
    currency: 'CNY',
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    region: 'Asia',
    subregion: 'East Asia',
    lat: 36.2048,
    lng: 138.2529,
    languages: ['ja'],
    faiths: ['Shintoism', 'Buddhism'],
    currency: 'JPY',
  },
  KR: {
    code: 'KR',
    name: 'South Korea',
    region: 'Asia',
    subregion: 'East Asia',
    lat: 35.9078,
    lng: 127.7669,
    languages: ['ko'],
    faiths: ['Christianity', 'Buddhism'],
    currency: 'KRW',
  },
  KP: {
    code: 'KP',
    name: 'North Korea',
    region: 'Asia',
    subregion: 'East Asia',
    lat: 40.3399,
    lng: 127.5101,
    languages: ['ko'],
    faiths: ['Traditional'],
    currency: 'KPW',
  },
  MN: {
    code: 'MN',
    name: 'Mongolia',
    region: 'Asia',
    subregion: 'East Asia',
    lat: 46.8625,
    lng: 103.8467,
    languages: ['mn'],
    faiths: ['Buddhism'],
    currency: 'MNT',
  },

  // ── Southeast Asia ──
  ID: {
    code: 'ID',
    name: 'Indonesia',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: -0.7893,
    lng: 113.9213,
    languages: ['id'],
    faiths: ['Islam'],
    currency: 'IDR',
  },
  PH: {
    code: 'PH',
    name: 'Philippines',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 12.8797,
    lng: 121.774,
    languages: ['tl', 'en'],
    faiths: ['Christianity'],
    currency: 'PHP',
  },
  VN: {
    code: 'VN',
    name: 'Vietnam',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 14.0583,
    lng: 108.2772,
    languages: ['vi'],
    faiths: ['Buddhism', 'Traditional'],
    currency: 'VND',
  },
  TH: {
    code: 'TH',
    name: 'Thailand',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 15.87,
    lng: 100.9925,
    languages: ['th'],
    faiths: ['Buddhism'],
    currency: 'THB',
  },
  MM: {
    code: 'MM',
    name: 'Myanmar',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 21.9162,
    lng: 95.956,
    languages: ['my'],
    faiths: ['Buddhism'],
    currency: 'MMK',
  },
  MY: {
    code: 'MY',
    name: 'Malaysia',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 4.2105,
    lng: 101.9758,
    languages: ['ms', 'en'],
    faiths: ['Islam', 'Buddhism', 'Christianity'],
    currency: 'MYR',
  },
  SG: {
    code: 'SG',
    name: 'Singapore',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 1.3521,
    lng: 103.8198,
    languages: ['en', 'ms', 'zh', 'ta'],
    faiths: ['Buddhism', 'Christianity', 'Islam'],
    currency: 'SGD',
  },
  KH: {
    code: 'KH',
    name: 'Cambodia',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 12.5657,
    lng: 104.991,
    languages: ['km'],
    faiths: ['Buddhism'],
    currency: 'KHR',
  },
  LA: {
    code: 'LA',
    name: 'Laos',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 19.8563,
    lng: 102.4955,
    languages: ['lo'],
    faiths: ['Buddhism'],
    currency: 'LAK',
  },
  BN: {
    code: 'BN',
    name: 'Brunei',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: 4.5353,
    lng: 114.7277,
    languages: ['ms'],
    faiths: ['Islam'],
    currency: 'BND',
  },
  TL: {
    code: 'TL',
    name: 'Timor-Leste',
    region: 'Asia',
    subregion: 'Southeast Asia',
    lat: -8.8742,
    lng: 125.7275,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'USD',
  },

  // ── South Asia ──
  IN: {
    code: 'IN',
    name: 'India',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 20.5937,
    lng: 78.9629,
    languages: ['hi', 'en', 'bn', 'ta', 'te', 'mr', 'gu', 'kn', 'ml', 'pa', 'ur'],
    faiths: ['Hinduism', 'Islam', 'Christianity', 'Sikhism'],
    currency: 'INR',
  },
  PK: {
    code: 'PK',
    name: 'Pakistan',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 30.3753,
    lng: 69.3451,
    languages: ['ur', 'en', 'pa'],
    faiths: ['Islam'],
    currency: 'PKR',
  },
  BD: {
    code: 'BD',
    name: 'Bangladesh',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 23.685,
    lng: 90.3563,
    languages: ['bn'],
    faiths: ['Islam', 'Hinduism'],
    currency: 'BDT',
  },
  LK: {
    code: 'LK',
    name: 'Sri Lanka',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 7.8731,
    lng: 80.7718,
    languages: ['si', 'ta'],
    faiths: ['Buddhism', 'Hinduism', 'Islam', 'Christianity'],
    currency: 'LKR',
  },
  NP: {
    code: 'NP',
    name: 'Nepal',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 28.3949,
    lng: 84.124,
    languages: ['ne'],
    faiths: ['Hinduism', 'Buddhism'],
    currency: 'NPR',
  },
  BT: {
    code: 'BT',
    name: 'Bhutan',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 27.5142,
    lng: 90.4336,
    languages: ['dz'],
    faiths: ['Buddhism'],
    currency: 'BTN',
  },
  MV: {
    code: 'MV',
    name: 'Maldives',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 3.2028,
    lng: 73.2207,
    languages: ['dv'],
    faiths: ['Islam'],
    currency: 'MVR',
  },
  AF: {
    code: 'AF',
    name: 'Afghanistan',
    region: 'Asia',
    subregion: 'South Asia',
    lat: 33.9391,
    lng: 67.71,
    languages: ['ps', 'fa'],
    faiths: ['Islam'],
    currency: 'AFN',
  },

  // ── Western Asia (Middle East) ──
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 23.8859,
    lng: 45.0792,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'SAR',
  },
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 23.4241,
    lng: 53.8478,
    languages: ['ar', 'en'],
    faiths: ['Islam'],
    currency: 'AED',
  },
  QA: {
    code: 'QA',
    name: 'Qatar',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 25.3548,
    lng: 51.1839,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'QAR',
  },
  KW: {
    code: 'KW',
    name: 'Kuwait',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 29.3117,
    lng: 47.4818,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'KWD',
  },
  BH: {
    code: 'BH',
    name: 'Bahrain',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 26.0667,
    lng: 50.5577,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'BHD',
  },
  OM: {
    code: 'OM',
    name: 'Oman',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 21.4735,
    lng: 55.9754,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'OMR',
  },
  YE: {
    code: 'YE',
    name: 'Yemen',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 15.5527,
    lng: 48.5164,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'YER',
  },
  IQ: {
    code: 'IQ',
    name: 'Iraq',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 33.2232,
    lng: 43.6793,
    languages: ['ar', 'ku'],
    faiths: ['Islam'],
    currency: 'IQD',
  },
  SY: {
    code: 'SY',
    name: 'Syria',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 34.8021,
    lng: 38.9968,
    languages: ['ar'],
    faiths: ['Islam', 'Christianity'],
    currency: 'SYP',
  },
  JO: {
    code: 'JO',
    name: 'Jordan',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 30.5852,
    lng: 36.2384,
    languages: ['ar'],
    faiths: ['Islam'],
    currency: 'JOD',
  },
  LB: {
    code: 'LB',
    name: 'Lebanon',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 33.8547,
    lng: 35.8623,
    languages: ['ar', 'fr'],
    faiths: ['Islam', 'Christianity'],
    currency: 'LBP',
  },
  IL: {
    code: 'IL',
    name: 'Israel',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 31.0461,
    lng: 34.8516,
    languages: ['he', 'ar'],
    faiths: ['Judaism', 'Islam'],
    currency: 'ILS',
  },
  // Palestine (PS) is a UN observer state, not a member state
  TR: {
    code: 'TR',
    name: 'Turkey',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 38.9637,
    lng: 35.2433,
    languages: ['tr'],
    faiths: ['Islam'],
    currency: 'TRY',
  },
  IR: {
    code: 'IR',
    name: 'Iran',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 32.4279,
    lng: 53.688,
    languages: ['fa'],
    faiths: ['Islam'],
    currency: 'IRR',
  },

  // ── Central Asia ──
  KZ: {
    code: 'KZ',
    name: 'Kazakhstan',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 48.0196,
    lng: 66.9237,
    languages: ['kk', 'ru'],
    faiths: ['Islam', 'Christianity'],
    currency: 'KZT',
  },
  UZ: {
    code: 'UZ',
    name: 'Uzbekistan',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 41.3775,
    lng: 64.5853,
    languages: ['uz'],
    faiths: ['Islam'],
    currency: 'UZS',
  },
  TM: {
    code: 'TM',
    name: 'Turkmenistan',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 38.9697,
    lng: 59.5563,
    languages: ['tk'],
    faiths: ['Islam'],
    currency: 'TMT',
  },
  TJ: {
    code: 'TJ',
    name: 'Tajikistan',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 38.861,
    lng: 71.2761,
    languages: ['tg'],
    faiths: ['Islam'],
    currency: 'TJS',
  },
  KG: {
    code: 'KG',
    name: 'Kyrgyzstan',
    region: 'Asia',
    subregion: 'Central Asia',
    lat: 41.2044,
    lng: 74.7661,
    languages: ['ky', 'ru'],
    faiths: ['Islam'],
    currency: 'KGS',
  },

  // ── Caucasus ──
  GE: {
    code: 'GE',
    name: 'Georgia',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 42.3154,
    lng: 43.3569,
    languages: ['ka'],
    faiths: ['Christianity'],
    currency: 'GEL',
  },
  AM: {
    code: 'AM',
    name: 'Armenia',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 40.0691,
    lng: 45.0382,
    languages: ['hy'],
    faiths: ['Christianity'],
    currency: 'AMD',
  },
  AZ: {
    code: 'AZ',
    name: 'Azerbaijan',
    region: 'Asia',
    subregion: 'Western Asia',
    lat: 40.1431,
    lng: 47.5769,
    languages: ['az'],
    faiths: ['Islam'],
    currency: 'AZN',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AMERICAS (35 countries)
  // ═══════════════════════════════════════════════════════════════════════════

  // ── North America ──
  US: {
    code: 'US',
    name: 'United States',
    region: 'Americas',
    subregion: 'North America',
    lat: 37.0902,
    lng: -95.7129,
    languages: ['en', 'es'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    region: 'Americas',
    subregion: 'North America',
    lat: 56.1304,
    lng: -106.3468,
    languages: ['en', 'fr'],
    faiths: ['Christianity'],
    currency: 'CAD',
  },
  MX: {
    code: 'MX',
    name: 'Mexico',
    region: 'Americas',
    subregion: 'North America',
    lat: 23.6345,
    lng: -102.5528,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'MXN',
  },

  // ── Central America ──
  GT: {
    code: 'GT',
    name: 'Guatemala',
    region: 'Americas',
    subregion: 'Central America',
    lat: 15.7835,
    lng: -90.2308,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'GTQ',
  },
  BZ: {
    code: 'BZ',
    name: 'Belize',
    region: 'Americas',
    subregion: 'Central America',
    lat: 17.1899,
    lng: -88.4976,
    languages: ['en', 'es'],
    faiths: ['Christianity'],
    currency: 'BZD',
  },
  HN: {
    code: 'HN',
    name: 'Honduras',
    region: 'Americas',
    subregion: 'Central America',
    lat: 15.2,
    lng: -86.2419,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'HNL',
  },
  SV: {
    code: 'SV',
    name: 'El Salvador',
    region: 'Americas',
    subregion: 'Central America',
    lat: 13.7942,
    lng: -88.8965,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  NI: {
    code: 'NI',
    name: 'Nicaragua',
    region: 'Americas',
    subregion: 'Central America',
    lat: 12.8654,
    lng: -85.2072,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'NIO',
  },
  CR: {
    code: 'CR',
    name: 'Costa Rica',
    region: 'Americas',
    subregion: 'Central America',
    lat: 9.7489,
    lng: -83.7534,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'CRC',
  },
  PA: {
    code: 'PA',
    name: 'Panama',
    region: 'Americas',
    subregion: 'Central America',
    lat: 8.538,
    lng: -80.7821,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'PAB',
  },

  // ── Caribbean ──
  CU: {
    code: 'CU',
    name: 'Cuba',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 21.5218,
    lng: -77.7812,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'CUP',
  },
  JM: {
    code: 'JM',
    name: 'Jamaica',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.1096,
    lng: -77.2975,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'JMD',
  },
  HT: {
    code: 'HT',
    name: 'Haiti',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.9712,
    lng: -72.2852,
    languages: ['fr', 'ht'],
    faiths: ['Christianity'],
    currency: 'HTG',
  },
  DO: {
    code: 'DO',
    name: 'Dominican Republic',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 18.7357,
    lng: -70.1627,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'DOP',
  },
  TT: {
    code: 'TT',
    name: 'Trinidad and Tobago',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 10.6918,
    lng: -61.2225,
    languages: ['en'],
    faiths: ['Christianity', 'Hinduism', 'Islam'],
    currency: 'TTD',
  },
  BB: {
    code: 'BB',
    name: 'Barbados',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 13.1939,
    lng: -59.5432,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'BBD',
  },
  BS: {
    code: 'BS',
    name: 'Bahamas',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 25.0343,
    lng: -77.3963,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'BSD',
  },
  GD: {
    code: 'GD',
    name: 'Grenada',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.1165,
    lng: -61.679,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },
  AG: {
    code: 'AG',
    name: 'Antigua and Barbuda',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 17.0608,
    lng: -61.7964,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },
  DM: {
    code: 'DM',
    name: 'Dominica',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 15.415,
    lng: -61.371,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },
  KN: {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 17.3578,
    lng: -62.783,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },
  LC: {
    code: 'LC',
    name: 'Saint Lucia',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 13.9094,
    lng: -60.9789,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },
  VC: {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    region: 'Americas',
    subregion: 'Caribbean',
    lat: 12.9843,
    lng: -61.2872,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'XCD',
  },

  // ── South America ──
  BR: {
    code: 'BR',
    name: 'Brazil',
    region: 'Americas',
    subregion: 'South America',
    lat: -14.235,
    lng: -51.9253,
    languages: ['pt'],
    faiths: ['Christianity'],
    currency: 'BRL',
  },
  AR: {
    code: 'AR',
    name: 'Argentina',
    region: 'Americas',
    subregion: 'South America',
    lat: -38.4161,
    lng: -63.6167,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'ARS',
  },
  CL: {
    code: 'CL',
    name: 'Chile',
    region: 'Americas',
    subregion: 'South America',
    lat: -35.6751,
    lng: -71.543,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'CLP',
  },
  CO: {
    code: 'CO',
    name: 'Colombia',
    region: 'Americas',
    subregion: 'South America',
    lat: 4.5709,
    lng: -74.2973,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'COP',
  },
  VE: {
    code: 'VE',
    name: 'Venezuela',
    region: 'Americas',
    subregion: 'South America',
    lat: 6.4238,
    lng: -66.5897,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'VES',
  },
  PE: {
    code: 'PE',
    name: 'Peru',
    region: 'Americas',
    subregion: 'South America',
    lat: -9.19,
    lng: -75.0152,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'PEN',
  },
  EC: {
    code: 'EC',
    name: 'Ecuador',
    region: 'Americas',
    subregion: 'South America',
    lat: -1.8312,
    lng: -78.1834,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  BO: {
    code: 'BO',
    name: 'Bolivia',
    region: 'Americas',
    subregion: 'South America',
    lat: -16.2902,
    lng: -63.5887,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'BOB',
  },
  PY: {
    code: 'PY',
    name: 'Paraguay',
    region: 'Americas',
    subregion: 'South America',
    lat: -23.4425,
    lng: -58.4438,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'PYG',
  },
  UY: {
    code: 'UY',
    name: 'Uruguay',
    region: 'Americas',
    subregion: 'South America',
    lat: -32.5228,
    lng: -55.7658,
    languages: ['es'],
    faiths: ['Christianity'],
    currency: 'UYU',
  },
  GY: {
    code: 'GY',
    name: 'Guyana',
    region: 'Americas',
    subregion: 'South America',
    lat: 4.8604,
    lng: -58.9302,
    languages: ['en'],
    faiths: ['Christianity', 'Hinduism', 'Islam'],
    currency: 'GYD',
  },
  SR: {
    code: 'SR',
    name: 'Suriname',
    region: 'Americas',
    subregion: 'South America',
    lat: 3.9193,
    lng: -56.0278,
    languages: ['nl'],
    faiths: ['Christianity', 'Hinduism', 'Islam'],
    currency: 'SRD',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OCEANIA (14 countries)
  // ═══════════════════════════════════════════════════════════════════════════

  AU: {
    code: 'AU',
    name: 'Australia',
    region: 'Oceania',
    subregion: 'Australasia',
    lat: -25.2744,
    lng: 133.7751,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'AUD',
  },
  NZ: {
    code: 'NZ',
    name: 'New Zealand',
    region: 'Oceania',
    subregion: 'Australasia',
    lat: -40.9006,
    lng: 174.886,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'NZD',
  },
  PG: {
    code: 'PG',
    name: 'Papua New Guinea',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -6.315,
    lng: 143.9555,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'PGK',
  },
  FJ: {
    code: 'FJ',
    name: 'Fiji',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -17.7134,
    lng: 178.065,
    languages: ['en'],
    faiths: ['Christianity', 'Hinduism'],
    currency: 'FJD',
  },
  SB: {
    code: 'SB',
    name: 'Solomon Islands',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -9.6457,
    lng: 160.1562,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'SBD',
  },
  VU: {
    code: 'VU',
    name: 'Vanuatu',
    region: 'Oceania',
    subregion: 'Melanesia',
    lat: -15.3767,
    lng: 166.9592,
    languages: ['en', 'fr'],
    faiths: ['Christianity'],
    currency: 'VUV',
  },
  WS: {
    code: 'WS',
    name: 'Samoa',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -13.759,
    lng: -172.1046,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'WST',
  },
  TO: {
    code: 'TO',
    name: 'Tonga',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -21.179,
    lng: -175.1982,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'TOP',
  },
  KI: {
    code: 'KI',
    name: 'Kiribati',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 1.8709,
    lng: -157.3626,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'AUD',
  },
  FM: {
    code: 'FM',
    name: 'Micronesia',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 7.4256,
    lng: 150.5508,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  MH: {
    code: 'MH',
    name: 'Marshall Islands',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 7.1315,
    lng: 171.1845,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  PW: {
    code: 'PW',
    name: 'Palau',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: 7.515,
    lng: 134.5825,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'USD',
  },
  NR: {
    code: 'NR',
    name: 'Nauru',
    region: 'Oceania',
    subregion: 'Micronesia',
    lat: -0.5228,
    lng: 166.9315,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'AUD',
  },
  TV: {
    code: 'TV',
    name: 'Tuvalu',
    region: 'Oceania',
    subregion: 'Polynesia',
    lat: -7.1095,
    lng: 177.6493,
    languages: ['en'],
    faiths: ['Christianity'],
    currency: 'AUD',
  },
}

// ─────────────────────────────────────────────────────────────────────────────
// ~70 Most Spoken Languages
// ─────────────────────────────────────────────────────────────────────────────

export const WORLD_LANGUAGES: Record<string, WorldLanguage> = {
  en: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'ltr',
    speakers: 1500,
    countries: ['US', 'GB', 'AU', 'CA', 'NZ', 'IE', 'KE', 'NG', 'ZA', 'IN', 'SG', 'PH', 'GH', 'JM'],
  },
  zh: {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    script: 'ltr',
    speakers: 1100,
    countries: ['CN', 'SG', 'MY'],
  },
  hi: {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'ltr',
    speakers: 600,
    countries: ['IN', 'NP', 'FJ'],
  },
  es: {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    script: 'ltr',
    speakers: 550,
    countries: ['ES', 'MX', 'CO', 'AR', 'PE', 'VE', 'CL', 'EC', 'GT', 'CU', 'BO', 'DO', 'HN', 'PY', 'SV', 'NI', 'CR', 'PA', 'UY', 'US', 'GQ'],
  },
  ar: {
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    script: 'rtl',
    speakers: 420,
    countries: ['SA', 'EG', 'IQ', 'MA', 'DZ', 'SD', 'SY', 'YE', 'TN', 'JO', 'LB', 'LY', 'AE', 'KW', 'OM', 'QA', 'BH', 'MR', 'DJ', 'KM', 'SO', 'ER', 'TD', 'IL'],
  },
  fr: {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    script: 'ltr',
    speakers: 310,
    countries: ['FR', 'CA', 'BE', 'CH', 'CD', 'CI', 'CM', 'SN', 'ML', 'BF', 'NE', 'GN', 'TG', 'BJ', 'CF', 'CG', 'GA', 'DJ', 'MG', 'HT', 'LU', 'MC', 'VU', 'RW', 'BI', 'TD'],
  },
  bn: {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'ltr',
    speakers: 270,
    countries: ['BD', 'IN'],
  },
  pt: {
    code: 'pt',
    name: 'Portuguese',
    nativeName: 'Português',
    script: 'ltr',
    speakers: 260,
    countries: ['BR', 'PT', 'AO', 'MZ', 'GW', 'CV', 'ST', 'TL', 'GQ'],
  },
  ru: {
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    script: 'ltr',
    speakers: 255,
    countries: ['RU', 'BY', 'KZ', 'KG'],
  },
  ja: {
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    script: 'ltr',
    speakers: 125,
    countries: ['JP'],
  },
  de: {
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    script: 'ltr',
    speakers: 130,
    countries: ['DE', 'AT', 'CH', 'LI', 'LU', 'BE'],
  },
  ko: {
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    script: 'ltr',
    speakers: 80,
    countries: ['KR', 'KP'],
  },
  tr: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    script: 'ltr',
    speakers: 80,
    countries: ['TR', 'CY'],
  },
  vi: {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    script: 'ltr',
    speakers: 85,
    countries: ['VN'],
  },
  it: {
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    script: 'ltr',
    speakers: 65,
    countries: ['IT', 'CH', 'SM', 'VA'],
  },
  pl: {
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    script: 'ltr',
    speakers: 45,
    countries: ['PL'],
  },
  uk: {
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    script: 'ltr',
    speakers: 40,
    countries: ['UA'],
  },
  nl: {
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    script: 'ltr',
    speakers: 25,
    countries: ['NL', 'BE', 'SR'],
  },
  sw: {
    code: 'sw',
    name: 'Swahili',
    nativeName: 'Kiswahili',
    script: 'ltr',
    speakers: 100,
    countries: ['KE', 'TZ', 'UG', 'CD', 'RW', 'BI'],
  },
  yo: {
    code: 'yo',
    name: 'Yoruba',
    nativeName: 'Yorùbá',
    script: 'ltr',
    speakers: 45,
    countries: ['NG', 'BJ'],
  },
  ha: {
    code: 'ha',
    name: 'Hausa',
    nativeName: 'Hausa',
    script: 'ltr',
    speakers: 80,
    countries: ['NG', 'NE', 'GH'],
  },
  am: {
    code: 'am',
    name: 'Amharic',
    nativeName: 'አማርኛ',
    script: 'ltr',
    speakers: 57,
    countries: ['ET'],
  },
  ig: {
    code: 'ig',
    name: 'Igbo',
    nativeName: 'Igbo',
    script: 'ltr',
    speakers: 45,
    countries: ['NG'],
  },
  zu: {
    code: 'zu',
    name: 'Zulu',
    nativeName: 'isiZulu',
    script: 'ltr',
    speakers: 28,
    countries: ['ZA'],
  },
  th: {
    code: 'th',
    name: 'Thai',
    nativeName: 'ภาษาไทย',
    script: 'ltr',
    speakers: 60,
    countries: ['TH'],
  },
  ms: {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Melayu',
    script: 'ltr',
    speakers: 77,
    countries: ['MY', 'SG', 'BN', 'ID'],
  },
  ta: {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'ltr',
    speakers: 80,
    countries: ['IN', 'LK', 'SG', 'MY'],
  },
  te: {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'ltr',
    speakers: 83,
    countries: ['IN'],
  },
  ur: {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'rtl',
    speakers: 230,
    countries: ['PK', 'IN'],
  },
  fa: {
    code: 'fa',
    name: 'Persian',
    nativeName: 'فارسی',
    script: 'rtl',
    speakers: 110,
    countries: ['IR', 'AF', 'TJ'],
  },
  he: {
    code: 'he',
    name: 'Hebrew',
    nativeName: 'עברית',
    script: 'rtl',
    speakers: 9,
    countries: ['IL'],
  },
  el: {
    code: 'el',
    name: 'Greek',
    nativeName: 'Ελληνικά',
    script: 'ltr',
    speakers: 13,
    countries: ['GR', 'CY'],
  },
  cs: {
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    script: 'ltr',
    speakers: 10,
    countries: ['CZ'],
  },
  ro: {
    code: 'ro',
    name: 'Romanian',
    nativeName: 'Română',
    script: 'ltr',
    speakers: 24,
    countries: ['RO', 'MD'],
  },
  hu: {
    code: 'hu',
    name: 'Hungarian',
    nativeName: 'Magyar',
    script: 'ltr',
    speakers: 13,
    countries: ['HU'],
  },
  sv: {
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    script: 'ltr',
    speakers: 10,
    countries: ['SE', 'FI'],
  },
  no: {
    code: 'no',
    name: 'Norwegian',
    nativeName: 'Norsk',
    script: 'ltr',
    speakers: 5,
    countries: ['NO'],
  },
  da: {
    code: 'da',
    name: 'Danish',
    nativeName: 'Dansk',
    script: 'ltr',
    speakers: 6,
    countries: ['DK'],
  },
  fi: {
    code: 'fi',
    name: 'Finnish',
    nativeName: 'Suomi',
    script: 'ltr',
    speakers: 5,
    countries: ['FI'],
  },
  id: {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    script: 'ltr',
    speakers: 200,
    countries: ['ID'],
  },
  tl: {
    code: 'tl',
    name: 'Filipino',
    nativeName: 'Filipino',
    script: 'ltr',
    speakers: 28,
    countries: ['PH'],
  },
  my: {
    code: 'my',
    name: 'Burmese',
    nativeName: 'မြန်မာဘာသာ',
    script: 'ltr',
    speakers: 33,
    countries: ['MM'],
  },
  km: {
    code: 'km',
    name: 'Khmer',
    nativeName: 'ខ្មែរ',
    script: 'ltr',
    speakers: 16,
    countries: ['KH'],
  },
  lo: {
    code: 'lo',
    name: 'Lao',
    nativeName: 'ລາວ',
    script: 'ltr',
    speakers: 7,
    countries: ['LA'],
  },
  si: {
    code: 'si',
    name: 'Sinhala',
    nativeName: 'සිංහල',
    script: 'ltr',
    speakers: 17,
    countries: ['LK'],
  },
  ne: {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    script: 'ltr',
    speakers: 25,
    countries: ['NP', 'IN'],
  },
  ps: {
    code: 'ps',
    name: 'Pashto',
    nativeName: 'پښتو',
    script: 'rtl',
    speakers: 50,
    countries: ['AF', 'PK'],
  },
  ku: {
    code: 'ku',
    name: 'Kurdish',
    nativeName: 'Kurdî',
    script: 'ltr',
    speakers: 30,
    countries: ['IQ', 'TR', 'IR', 'SY'],
  },
  az: {
    code: 'az',
    name: 'Azerbaijani',
    nativeName: 'Azərbaycan dili',
    script: 'ltr',
    speakers: 23,
    countries: ['AZ'],
  },
  uz: {
    code: 'uz',
    name: 'Uzbek',
    nativeName: "O'zbek tili",
    script: 'ltr',
    speakers: 27,
    countries: ['UZ'],
  },
  kk: {
    code: 'kk',
    name: 'Kazakh',
    nativeName: 'Қазақ тілі',
    script: 'ltr',
    speakers: 13,
    countries: ['KZ'],
  },
  ka: {
    code: 'ka',
    name: 'Georgian',
    nativeName: 'ქართული',
    script: 'ltr',
    speakers: 4,
    countries: ['GE'],
  },
  hy: {
    code: 'hy',
    name: 'Armenian',
    nativeName: 'Հայերեն',
    script: 'ltr',
    speakers: 7,
    countries: ['AM'],
  },
  mn: {
    code: 'mn',
    name: 'Mongolian',
    nativeName: 'Монгол',
    script: 'ltr',
    speakers: 6,
    countries: ['MN'],
  },
  ml: {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'ltr',
    speakers: 38,
    countries: ['IN'],
  },
  kn: {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'ltr',
    speakers: 44,
    countries: ['IN'],
  },
  gu: {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'ltr',
    speakers: 57,
    countries: ['IN'],
  },
  mr: {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'ltr',
    speakers: 83,
    countries: ['IN'],
  },
  pa: {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'ltr',
    speakers: 113,
    countries: ['IN', 'PK'],
  },
  rw: {
    code: 'rw',
    name: 'Kinyarwanda',
    nativeName: 'Ikinyarwanda',
    script: 'ltr',
    speakers: 12,
    countries: ['RW', 'BI'],
  },
  so: {
    code: 'so',
    name: 'Somali',
    nativeName: 'Soomaali',
    script: 'ltr',
    speakers: 22,
    countries: ['SO', 'DJ', 'ET', 'KE'],
  },
  mg: {
    code: 'mg',
    name: 'Malagasy',
    nativeName: 'Malagasy',
    script: 'ltr',
    speakers: 25,
    countries: ['MG'],
  },
  ti: {
    code: 'ti',
    name: 'Tigrinya',
    nativeName: 'ትግርኛ',
    script: 'ltr',
    speakers: 9,
    countries: ['ER', 'ET'],
  },
  // Additional widely spoken languages
  sr: {
    code: 'sr',
    name: 'Serbian',
    nativeName: 'Српски',
    script: 'ltr',
    speakers: 12,
    countries: ['RS', 'BA', 'ME'],
  },
  hr: {
    code: 'hr',
    name: 'Croatian',
    nativeName: 'Hrvatski',
    script: 'ltr',
    speakers: 5,
    countries: ['HR', 'BA'],
  },
  sk: {
    code: 'sk',
    name: 'Slovak',
    nativeName: 'Slovenčina',
    script: 'ltr',
    speakers: 5,
    countries: ['SK'],
  },
  bg: {
    code: 'bg',
    name: 'Bulgarian',
    nativeName: 'Български',
    script: 'ltr',
    speakers: 8,
    countries: ['BG'],
  },
  sq: {
    code: 'sq',
    name: 'Albanian',
    nativeName: 'Shqip',
    script: 'ltr',
    speakers: 7,
    countries: ['AL', 'MK'],
  },
  mk: {
    code: 'mk',
    name: 'Macedonian',
    nativeName: 'Македонски',
    script: 'ltr',
    speakers: 2,
    countries: ['MK'],
  },
  sl: {
    code: 'sl',
    name: 'Slovenian',
    nativeName: 'Slovenščina',
    script: 'ltr',
    speakers: 2,
    countries: ['SI'],
  },
  bs: {
    code: 'bs',
    name: 'Bosnian',
    nativeName: 'Bosanski',
    script: 'ltr',
    speakers: 3,
    countries: ['BA'],
  },
  be: {
    code: 'be',
    name: 'Belarusian',
    nativeName: 'Беларуская',
    script: 'ltr',
    speakers: 5,
    countries: ['BY'],
  },
  is: {
    code: 'is',
    name: 'Icelandic',
    nativeName: 'Íslenska',
    script: 'ltr',
    speakers: 0.3,
    countries: ['IS'],
  },
  mt: {
    code: 'mt',
    name: 'Maltese',
    nativeName: 'Malti',
    script: 'ltr',
    speakers: 0.5,
    countries: ['MT'],
  },
  et: {
    code: 'et',
    name: 'Estonian',
    nativeName: 'Eesti',
    script: 'ltr',
    speakers: 1,
    countries: ['EE'],
  },
  lv: {
    code: 'lv',
    name: 'Latvian',
    nativeName: 'Latviešu',
    script: 'ltr',
    speakers: 2,
    countries: ['LV'],
  },
  lt: {
    code: 'lt',
    name: 'Lithuanian',
    nativeName: 'Lietuvių',
    script: 'ltr',
    speakers: 3,
    countries: ['LT'],
  },
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Get a country's display name using Intl.DisplayNames with fallback.
 * @param code ISO 3166-1 alpha-2 country code
 * @param locale BCP 47 locale string (e.g. 'en', 'de', 'fr')
 */
export function getCountryName(code: string, locale: string = 'en'): string {
  try {
    const displayNames = new Intl.DisplayNames([locale], { type: 'region' })
    const name = displayNames.of(code.toUpperCase())
    if (name) return name
  } catch {
    // Intl.DisplayNames not available or code not recognized — fall through
  }
  return WORLD_COUNTRIES[code.toUpperCase()]?.name ?? code
}

/**
 * Get a language's English name from the registry.
 */
export function getLanguageName(code: string): string {
  return WORLD_LANGUAGES[code.toLowerCase()]?.name ?? code
}

/**
 * Get all countries in a given region.
 */
export function getCountriesByRegion(region: string): WorldCountry[] {
  return Object.values(WORLD_COUNTRIES).filter(
    (c) => c.region.toLowerCase() === region.toLowerCase()
  )
}

/**
 * Get full language objects for all languages spoken in a country.
 */
export function getLanguagesForCountry(countryCode: string): WorldLanguage[] {
  const country = WORLD_COUNTRIES[countryCode.toUpperCase()]
  if (!country) return []
  return country.languages
    .map((langCode) => WORLD_LANGUAGES[langCode])
    .filter(Boolean)
}
