import { NextResponse } from 'next/server'
import { logger } from '@/lib/logger'

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as { event?: string; data?: unknown }

    // Verify webhook secret
    const secret = request.headers.get('x-webhook-secret')
    if (process.env.N8N_WEBHOOK_SECRET && secret !== process.env.N8N_WEBHOOK_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { event, data } = body
    logger.info('n8n webhook received', { event })

    switch (event) {
      case 'social_posted':
        // n8n confirms social media post was published
        logger.info('Social post published via n8n', { data })
        return NextResponse.json({ received: true, event })

      case 'content_generated':
        // n8n generated content for review — log for manual approval
        logger.info('Content generated by n8n for review', { data })
        return NextResponse.json({ received: true, event })

      default:
        logger.debug('Unknown n8n webhook event', { event })
        return NextResponse.json({ received: true, event: 'unknown' })
    }
  } catch {
    return NextResponse.json({ error: 'Invalid payload' }, { status: 400 })
  }
}
